name: gid_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_secure_storage: ^8.0.0
  email_validator: ^2.1.17
  supabase_flutter: ^1.0.0
  url_launcher: ^6.1.11
  http: ^0.13.5


flutter:
  uses-material-design: true
